# Generated by Django 5.2.5 on 2025-08-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_buyrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='status',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='collected',
            field=models.BooleanField(default=False),
        ),
    ]
