# Generated by Django 5.2.5 on 2025-11-10 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSnapshot',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('price', models.FloatField(null=True)),
                ('shares', models.BigIntegerField(null=True)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('pe', models.FloatField(null=True)),
                ('yld', models.FloatField(null=True)),
                ('as_of', models.DateTimeField(db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='buyrecord',
            name='stock_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='stock_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='stock_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
