# Generated by Django 5.2.5 on 2025-11-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_stocksnapshot_alter_buyrecord_stock_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocksnapshot',
            name='as_of',
        ),
        migrations.RemoveField(
            model_name='stocksnapshot',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='stocksnapshot',
            name='yld',
        ),
        migrations.AddField(
            model_name='stocksnapshot',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksnapshot',
            name='dividend_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='stocksnapshot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stocksnapshot',
            name='code',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='stocksnapshot',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stocksnapshot',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stocksnapshot',
            name='pe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stocksnapshot',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='stocksnapshot',
            name='shares',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
