# Generated by Django 5.2.5 on 2025-11-10 15:04

from django.db import migrations
from django.utils import timezone

def fill_created_at(apps, schema_editor):
    Snapshot = apps.get_model('main', 'StockSnapshot')
    Snapshot.objects.filter(created_at__isnull=True).update(created_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_stocksnapshot_as_of_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_created_at, reverse_code=migrations.RunPython.noop),
    ]
