# Generated by Django 5.2.5 on 2025-11-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_fill_snapshot_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksnapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
