# Generated by Django 5.2.5 on 2025-11-12 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_stocksnapshot_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyrecord',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='buyrecord',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='buyrecord_quantity_nonzero'),
        ),
    ]
