# Generated by Django 5.2.5 on 2025-11-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_buyrecord_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
