# Generated by Django 5.2.5 on 2025-11-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('share', '分享'), ('analysis', '分析'), ('qa', '問答')], default='share', max_length=20),
        ),
    ]
